export const CHANGE_ACTIVE_COUNT = 'CHANGE_ACTIVE_COUNT';
export const CHANGE_ARCHIVED_COUNT = 'CHANGE_ARCHIVED_COUNT';

export const CREATE_NOTE = 'CREATE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const TOGGLE_NOTE_ARCHIVING = 'TOGGLE_NOTE_ARCHIVING';
export const DELETE_ALL_NOTES = 'DELETE_ALL_NOTES';
export const TOGGLE_ALL_NOTES_ARCHIVING = 'ARCIVATE_ALL_NOTES';

export const CHANGE_NOTES_TABLE_TYPE = 'CHANGE_NOTES_TABLE_TYPE';
export const TOGGLE_POPUP = 'TOGGLE_POPUP';