export const CHANGE_ACTIVE_COUNT = 'CHANGE_ACTIVE_COUNT';
export const CHANGE_ARCHIVED_COUNT = 'CHANGE_ARCHIVED_COUNT';

export const CREATE_NOTE = 'CREATE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const ARCHIVATE_NOTE = 'ARCHIVATE_NOTE';
export const UNARCHIVATE_NOTE = 'UNARCHIVATE_NOTE';

export const CHANGE_NOTES_TABLE_TYPE = 'CHANGE_NOTES_TABLE_TYPE';
export const TOGGLE_POPUP = 'TOGGLE_POPUP';